# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets exec'd

from rsg.rsgGui import *
from abaqusConstants import *
from abaqusGui import *


#################################################################

vpName = session.currentViewportName
modelName = session.sessionState[vpName]['modelName']
    
ass = mdb.models[modelName].rootAssembly


## Connector Section

dictx = mdb.models[modelName].sections
csections = []
    
for x in dictx.keys():
    try:
        s=dictx[x].behaviorOptions
        csections.append(dictx[x].name)
    except:
        pass

if len(csections)<1:
    csections = ['None. Create new is used']

defaultcsectionname = csections[0]

################################################################



dialogBox = RsgDialog(title='Connection Builder', kernelModule='CB_module', kernelFunction='CB_function', includeApplyBtn=True, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=thisDir)
RsgTextField(p='DialogBox', fieldType='String', ncols=25, labelText='Name prefix: ', keyword='kw_name', default='CNTN-')
RsgGroupBox(name='GroupBox_1', p='DialogBox', text='Region A', layout='LAYOUT_FILL_X')
RsgPickButton(p='GroupBox_1', text='Select faces: ', keyword='kw_faces_A', prompt='Pick one or multiple faces', entitiesToPick='MDB_GEOMETRY|FACES', numberToPick='MANY')
RsgComboBox(name='ComboBox_5', p='GroupBox_1', text='Coupling type: ', keyword='kw_coupling_A', default='Distributing', comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
RsgListItem(p='ComboBox_5', text='Distributing')
RsgListItem(p='ComboBox_5', text='Kinematic')
RsgCheckButton(p='GroupBox_1', text='Create surface and set', keyword='kw_setregion_A', default=False)
RsgSeparator(p='DialogBox')
RsgGroupBox(name='GroupBox_2', p='DialogBox', text='Region B', layout='LAYOUT_FILL_X')
RsgPickButton(p='GroupBox_2', text='Select faces: ', keyword='kw_faces_B', prompt='Pick one or multiple faces', entitiesToPick='MDB_GEOMETRY|FACES', numberToPick='MANY')
RsgComboBox(name='ComboBox_6', p='GroupBox_2', text='Coupling type: ', keyword='kw_coupling_B', default='Distributing', comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
RsgListItem(p='ComboBox_6', text='Distributing')
RsgListItem(p='ComboBox_6', text='Kinematic')
RsgCheckButton(p='GroupBox_2', text='Create surface and set', keyword='kw_setregion_B', default=False)
RsgSeparator(p='DialogBox')
RsgGroupBox(name='GroupBox_3', p='DialogBox', text='Connector Section', layout='LAYOUT_FILL_X')
RsgRadioButton(p='GroupBox_3', text='Reuse existing connector section', keyword='kw_rb_section', default=True)

RsgComboBox(name='ComboBox_2', p='GroupBox_3', text='Select: ', keyword='kw_pd_reuse_section', default=defaultcsectionname, comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
for x in csections:
    RsgListItem(p='ComboBox_2', text=x)

#RsgComboBox(name='ComboBox_2', p='GroupBox_3', text='Select: ', keyword='kw_pd_reuse_section', default='Item 1', comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
#RsgListItem(p='ComboBox_2', text='Item 1')
#RsgListItem(p='ComboBox_2', text='Item 2')
#RsgListItem(p='ComboBox_2', text='Item 3')

RsgRadioButton(p='GroupBox_3', text='Create new connector section', keyword='kw_rb_section', default=False)
RsgComboBox(name='ComboBox_3', p='GroupBox_3', text='Select: ', keyword='kw_pd_new_section', default='Translator', comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
RsgListItem(p='ComboBox_3', text='Translator')
RsgListItem(p='ComboBox_3', text='Cylindrical')
RsgListItem(p='ComboBox_3', text='Hinge')
RsgListItem(p='ComboBox_3', text='Axial')
RsgListItem(p='ComboBox_3', text='Beam')
RsgCheckButton(p='GroupBox_3', text='Create set with wire', keyword='kw_create_wireset', default=True)
dialogBox.show()
